### PR TITLE
Implement initial auth pages

### LINKED ISSUE #3: Implement initial auth pages: sign in and sign up (Formik wise)
# Description
- Our authRoutes rely on these two pages: sign in has a 2 field form (email, password) and sign up has 4 fields ()

#  Prerequisites
- add [Yup](https://formik.org/docs/tutorial#schema-validation-with-yup) and [Formik](https://formik.org/docs/overview) 
- make both pages using flowbite-react components like <TextInput/> or <Button/>
- validate the form inputs using Yup's schema inside Formik

# Additional Info
- make it like our previous projects such as 'react-bombado-bucha'

### PR DESCRIPTION
**Pull request by zogss**
#3 
- Initial auth pages implementation

# Proposed Changes
- add Yup and Formik
- add Sign In and Sign Up pages
- add flowbite-react components in both pages
- validating form input using Formik and Yup in both pages

# Screenshots

image
image

image
image

### CODE REVIEW

**Review by Manuel-Antunes — CHANGES_REQUESTED** [review]
i need the mobile screenshots with the responsiveness

**Comment by Manuel-Antunes** [comment]
Man, the base of this branch is wrong, i think this branch doesn't merges in main, please solve it.

**Comment by zogss** [comment]
> i need the mobile screenshots with the responsiveness

- screenshots added

> Man, the base of this branch is wrong, i think this branch doesn't merges in main, please solve it.

- base branch changed

**Review by Manuel-Antunes — APPROVED** [review]
ok

**Pull request merged**
